//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Detailedbills = new HashSet<Detailedbill>();
        }
    
        public int BillId { get; set; }
        public int StatusId { get; set; }
        public int IdCustomer { get; set; }
        public decimal PriceBill { get; set; }
        public System.DateTime DateBill { get; set; }
        public Nullable<int> IdVoucher { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Statuss Statuss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detailedbill> Detailedbills { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
