//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailedbill
    {
        public int DetailedbillsId { get; set; }
        public int ProductId { get; set; }
        public int BillId { get; set; }
        public int IdUser { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
