//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Detailedbills = new HashSet<Detailedbill>();
        }
    
        public int IdUser { get; set; }
        public string UserName { get; set; }
        public string UserAddress { get; set; }
        public string SDT { get; set; }
        public System.DateTime UserAge { get; set; }
        public string Email { get; set; }
        public int IdTaiKhoan { get; set; }
        public Nullable<bool> UsesGend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detailedbill> Detailedbills { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
